from django.urls import include, path
from utilities.urls import get_model_urls

from .views import (
    combined,
    dhcp_control,
    dhcp_plugin_sync,
    leases,
    options,
    reservation_mutations,
    server,
    shared_networks,
    subnets,
    sync_jobs,
    sync_views,
)

urlpatterns = (
    path("combined/", combined.CombinedDashboardView.as_view(), name="combined"),
    path("combined/leases4/", combined.CombinedLeases4View.as_view(), name="combined_leases4"),
    path("combined/leases6/", combined.CombinedLeases6View.as_view(), name="combined_leases6"),
    path("combined/subnets4/", combined.CombinedSubnets4View.as_view(), name="combined_subnets4"),
    path("combined/subnets6/", combined.CombinedSubnets6View.as_view(), name="combined_subnets6"),
    path(
        "combined/shared-networks4/",
        combined.CombinedSharedNetworks4View.as_view(),
        name="combined_shared_networks4",
    ),
    path(
        "combined/shared-networks6/",
        combined.CombinedSharedNetworks6View.as_view(),
        name="combined_shared_networks6",
    ),
    path(
        "combined/reservations4/",
        combined.CombinedReservations4View.as_view(),
        name="combined_reservations4",
    ),
    path(
        "combined/reservations6/",
        combined.CombinedReservations6View.as_view(),
        name="combined_reservations6",
    ),
    path(
        "combined/server-status-badge/<int:pk>/",
        options.CombinedServerStatusBadgeView.as_view(),
        name="combined_server_status_badge",
    ),
    path("sync-jobs/", sync_jobs.SyncJobsView.as_view(), name="sync_jobs"),
    path("servers/<int:pk>/sync-now/", sync_jobs.ServerSyncNowView.as_view(), name="server_sync_now"),
    path("servers/<int:pk>/sync-toggle/", sync_jobs.ServerSyncToggleView.as_view(), name="server_sync_toggle"),
    path(
        "servers/<int:pk>/dhcp-plugin/sync/",
        dhcp_plugin_sync.ServerDhcpPluginSyncNowView.as_view(),
        name="server_dhcp_plugin_sync",
    ),
    path("servers/", server.ServerListView.as_view(), name="server_list"),
    path("servers/add/", server.ServerEditView.as_view(), name="server_add"),
    path(
        "servers/delete/",
        server.ServerBulkDeleteView.as_view(),
        name="server_bulk_delete",
    ),
    path(
        "servers/edit/",
        server.ServerBulkEditView.as_view(),
        name="server_bulk_edit",
    ),
    path(
        "servers/import/",
        server.ServerBulkImportView.as_view(),
        name="server_bulk_import",
    ),
    path(
        "servers/<int:pk>/leases4/add/",
        leases.ServerLease4AddView.as_view(),
        name="server_lease4_add",
    ),
    path(
        "servers/<int:pk>/leases6/add/",
        leases.ServerLease6AddView.as_view(),
        name="server_lease6_add",
    ),
    path(
        "servers/<int:pk>/leases6/delete/",
        leases.ServerLeases6DeleteView.as_view(),
        name="server_leases6_delete",
    ),
    path(
        "servers/<int:pk>/leases4/delete/",
        leases.ServerLeases4DeleteView.as_view(),
        name="server_leases4_delete",
    ),
    path(
        "servers/<int:pk>/reservation/check-ip/",
        sync_views.ReservationCheckNetboxIPView.as_view(),
        name="reservation_check_ip",
    ),
    path(
        "servers/<int:pk>/reservations4/add/",
        reservation_mutations.ServerReservation4AddView.as_view(),
        name="server_reservation4_add",
    ),
    path(
        "servers/<int:pk>/reservations4/<int:subnet_id>/edit/",
        reservation_mutations.ServerReservation4EditView.as_view(),
        name="server_reservation4_edit",
    ),
    path(
        "servers/<int:pk>/reservations4/<int:subnet_id>/delete/",
        reservation_mutations.ServerReservation4DeleteView.as_view(),
        name="server_reservation4_delete",
    ),
    path(
        "servers/<int:pk>/reservations6/add/",
        reservation_mutations.ServerReservation6AddView.as_view(),
        name="server_reservation6_add",
    ),
    path(
        "servers/<int:pk>/reservations6/<int:subnet_id>/edit/",
        reservation_mutations.ServerReservation6EditView.as_view(),
        name="server_reservation6_edit",
    ),
    path(
        "servers/<int:pk>/reservations6/<int:subnet_id>/delete/",
        reservation_mutations.ServerReservation6DeleteView.as_view(),
        name="server_reservation6_delete",
    ),
    path(
        "servers/<int:pk>/leases4/sync/",
        sync_views.ServerLease4SyncView.as_view(),
        name="server_lease4_sync",
    ),
    path(
        "servers/<int:pk>/leases6/sync/",
        sync_views.ServerLease6SyncView.as_view(),
        name="server_lease6_sync",
    ),
    path(
        "servers/<int:pk>/reservations4/<int:subnet_id>/sync/",
        sync_views.ServerReservation4SyncView.as_view(),
        name="server_reservation4_sync",
    ),
    path(
        "servers/<int:pk>/reservations6/<int:subnet_id>/sync/",
        sync_views.ServerReservation6SyncView.as_view(),
        name="server_reservation6_sync",
    ),
    path(
        "servers/<int:pk>/reservations4/bulk-sync/",
        sync_views.ServerReservation4BulkSyncView.as_view(),
        name="server_reservation4_bulk_sync",
    ),
    path(
        "servers/<int:pk>/reservations6/bulk-sync/",
        sync_views.ServerReservation6BulkSyncView.as_view(),
        name="server_reservation6_bulk_sync",
    ),
    path(
        "servers/<int:pk>/reservations4/import/",
        sync_views.ServerReservation4BulkImportView.as_view(),
        name="server_reservation4_bulk_import",
    ),
    path(
        "servers/<int:pk>/reservations6/import/",
        sync_views.ServerReservation6BulkImportView.as_view(),
        name="server_reservation6_bulk_import",
    ),
    path(
        "servers/<int:pk>/leases4/import/",
        sync_views.ServerLease4BulkImportView.as_view(),
        name="server_lease4_bulk_import",
    ),
    path(
        "servers/<int:pk>/leases6/import/",
        sync_views.ServerLease6BulkImportView.as_view(),
        name="server_lease6_bulk_import",
    ),
    path(
        "servers/<int:pk>/subnets4/<int:subnet_id>/pools/add/",
        subnets.ServerSubnet4PoolAddView.as_view(),
        name="server_subnet4_pool_add",
    ),
    path(
        "servers/<int:pk>/subnets4/<int:subnet_id>/pools/<path:pool>/delete/",
        subnets.ServerSubnet4PoolDeleteView.as_view(),
        name="server_subnet4_pool_delete",
    ),
    path(
        "servers/<int:pk>/subnets6/<int:subnet_id>/pools/add/",
        subnets.ServerSubnet6PoolAddView.as_view(),
        name="server_subnet6_pool_add",
    ),
    path(
        "servers/<int:pk>/subnets6/<int:subnet_id>/pools/<path:pool>/delete/",
        subnets.ServerSubnet6PoolDeleteView.as_view(),
        name="server_subnet6_pool_delete",
    ),
    path(
        "servers/<int:pk>/subnets4/add/",
        subnets.ServerSubnet4AddView.as_view(),
        name="server_subnet4_add",
    ),
    path(
        "servers/<int:pk>/subnets4/<int:subnet_id>/edit/",
        subnets.ServerSubnet4EditView.as_view(),
        name="server_subnet4_edit",
    ),
    path(
        "servers/<int:pk>/subnets4/<int:subnet_id>/delete/",
        subnets.ServerSubnet4DeleteView.as_view(),
        name="server_subnet4_delete",
    ),
    path(
        "servers/<int:pk>/subnets4/<int:subnet_id>/wipe/",
        subnets.ServerSubnet4WipeView.as_view(),
        name="server_subnet4_wipe_leases",
    ),
    path(
        "servers/<int:pk>/subnets6/add/",
        subnets.ServerSubnet6AddView.as_view(),
        name="server_subnet6_add",
    ),
    path(
        "servers/<int:pk>/subnets6/<int:subnet_id>/edit/",
        subnets.ServerSubnet6EditView.as_view(),
        name="server_subnet6_edit",
    ),
    path(
        "servers/<int:pk>/subnets6/<int:subnet_id>/delete/",
        subnets.ServerSubnet6DeleteView.as_view(),
        name="server_subnet6_delete",
    ),
    path(
        "servers/<int:pk>/subnets6/<int:subnet_id>/wipe/",
        subnets.ServerSubnet6WipeView.as_view(),
        name="server_subnet6_wipe_leases",
    ),
    path(
        "servers/<int:pk>/subnets4/<int:subnet_id>/options/",
        options.ServerSubnet4OptionsEditView.as_view(),
        name="server_subnet4_options_edit",
    ),
    path(
        "servers/<int:pk>/subnets6/<int:subnet_id>/options/",
        options.ServerSubnet6OptionsEditView.as_view(),
        name="server_subnet6_options_edit",
    ),
    path(
        "servers/<int:pk>/dhcp4/enable/",
        dhcp_control.ServerDHCP4EnableView.as_view(),
        name="server_dhcp4_enable",
    ),
    path(
        "servers/<int:pk>/dhcp4/disable/",
        dhcp_control.ServerDHCP4DisableView.as_view(),
        name="server_dhcp4_disable",
    ),
    path(
        "servers/<int:pk>/dhcp6/enable/",
        dhcp_control.ServerDHCP6EnableView.as_view(),
        name="server_dhcp6_enable",
    ),
    path(
        "servers/<int:pk>/dhcp6/disable/",
        dhcp_control.ServerDHCP6DisableView.as_view(),
        name="server_dhcp6_disable",
    ),
    path(
        "servers/<int:pk>/dhcp4/options/",
        options.ServerDHCP4OptionsEditView.as_view(),
        name="server_dhcp4_options_edit",
    ),
    path(
        "servers/<int:pk>/dhcp6/options/",
        options.ServerDHCP6OptionsEditView.as_view(),
        name="server_dhcp6_options_edit",
    ),
    path(
        "servers/<int:pk>/shared-networks4/add/",
        shared_networks.ServerSharedNetwork4AddView.as_view(),
        name="server_shared_network4_add",
    ),
    path(
        "servers/<int:pk>/shared-networks6/add/",
        shared_networks.ServerSharedNetwork6AddView.as_view(),
        name="server_shared_network6_add",
    ),
    path(
        "servers/<int:pk>/shared-networks4/<str:network_name>/delete/",
        shared_networks.ServerSharedNetwork4DeleteView.as_view(),
        name="server_shared_network4_delete",
    ),
    path(
        "servers/<int:pk>/shared-networks6/<str:network_name>/delete/",
        shared_networks.ServerSharedNetwork6DeleteView.as_view(),
        name="server_shared_network6_delete",
    ),
    path(
        "servers/<int:pk>/shared-networks4/<str:network_name>/edit/",
        shared_networks.ServerSharedNetwork4EditView.as_view(),
        name="server_shared_network4_edit",
    ),
    path(
        "servers/<int:pk>/shared-networks6/<str:network_name>/edit/",
        shared_networks.ServerSharedNetwork6EditView.as_view(),
        name="server_shared_network6_edit",
    ),
    path(
        "servers/<int:pk>/dhcp4/option-def/",
        options.ServerOptionDef4View.as_view(),
        name="server_option_def4",
    ),
    path(
        "servers/<int:pk>/dhcp6/option-def/",
        options.ServerOptionDef6View.as_view(),
        name="server_option_def6",
    ),
    path(
        "servers/<int:pk>/dhcp4/option-def/add/",
        options.ServerOptionDef4AddView.as_view(),
        name="server_option_def4_add",
    ),
    path(
        "servers/<int:pk>/dhcp6/option-def/add/",
        options.ServerOptionDef6AddView.as_view(),
        name="server_option_def6_add",
    ),
    path(
        "servers/<int:pk>/dhcp4/option-def/<int:code>/<str:space>/delete/",
        options.ServerOptionDef4DeleteView.as_view(),
        name="server_option_def4_delete",
    ),
    path(
        "servers/<int:pk>/dhcp6/option-def/<int:code>/<str:space>/delete/",
        options.ServerOptionDef6DeleteView.as_view(),
        name="server_option_def6_delete",
    ),
    path("servers/<int:pk>/", include(get_model_urls("netbox_kea", "server"))),
    path(
        "ip-addresses/<int:pk>/kea-reservations/",
        options.IPAddressKeaReservationsView.as_view(),
        name="ipaddress_kea_reservations",
    ),
)
