from django.urls import include, path
from utilities.urls import get_model_urls

from . import views

urlpatterns = (
    path("combined/", views.CombinedDashboardView.as_view(), name="combined"),
    path("combined/leases4/", views.CombinedLeases4View.as_view(), name="combined_leases4"),
    path("combined/leases6/", views.CombinedLeases6View.as_view(), name="combined_leases6"),
    path("combined/subnets4/", views.CombinedSubnets4View.as_view(), name="combined_subnets4"),
    path("combined/subnets6/", views.CombinedSubnets6View.as_view(), name="combined_subnets6"),
    path(
        "combined/shared-networks4/",
        views.CombinedSharedNetworks4View.as_view(),
        name="combined_shared_networks4",
    ),
    path(
        "combined/shared-networks6/",
        views.CombinedSharedNetworks6View.as_view(),
        name="combined_shared_networks6",
    ),
    path(
        "combined/reservations4/",
        views.CombinedReservations4View.as_view(),
        name="combined_reservations4",
    ),
    path(
        "combined/reservations6/",
        views.CombinedReservations6View.as_view(),
        name="combined_reservations6",
    ),
    path(
        "combined/server-status-badge/<int:pk>/",
        views.CombinedServerStatusBadgeView.as_view(),
        name="combined_server_status_badge",
    ),
    path("servers/", views.ServerListView.as_view(), name="server_list"),
    path("servers/add/", views.ServerEditView.as_view(), name="server_add"),
    path(
        "servers/delete/",
        views.ServerBulkDeleteView.as_view(),
        name="server_bulk_delete",
    ),
    path(
        "servers/edit/",
        views.ServerBulkEditView.as_view(),
        name="server_bulk_edit",
    ),
    path(
        "servers/import/",
        views.ServerBulkImportView.as_view(),
        name="server_bulk_import",
    ),
    path(
        "servers/<int:pk>/leases4/add/",
        views.ServerLease4AddView.as_view(),
        name="server_lease4_add",
    ),
    path(
        "servers/<int:pk>/leases6/add/",
        views.ServerLease6AddView.as_view(),
        name="server_lease6_add",
    ),
    path(
        "servers/<int:pk>/leases6/delete/",
        views.ServerLeases6DeleteView.as_view(),
        name="server_leases6_delete",
    ),
    path(
        "servers/<int:pk>/leases4/delete/",
        views.ServerLeases4DeleteView.as_view(),
        name="server_leases4_delete",
    ),
    path(
        "servers/<int:pk>/reservations4/add/",
        views.ServerReservation4AddView.as_view(),
        name="server_reservation4_add",
    ),
    path(
        "servers/<int:pk>/reservations4/<int:subnet_id>/<str:ip_address>/edit/",
        views.ServerReservation4EditView.as_view(),
        name="server_reservation4_edit",
    ),
    path(
        "servers/<int:pk>/reservations4/<int:subnet_id>/<str:ip_address>/delete/",
        views.ServerReservation4DeleteView.as_view(),
        name="server_reservation4_delete",
    ),
    path(
        "servers/<int:pk>/reservations6/add/",
        views.ServerReservation6AddView.as_view(),
        name="server_reservation6_add",
    ),
    path(
        "servers/<int:pk>/reservations6/<int:subnet_id>/<str:ip_address>/edit/",
        views.ServerReservation6EditView.as_view(),
        name="server_reservation6_edit",
    ),
    path(
        "servers/<int:pk>/reservations6/<int:subnet_id>/<str:ip_address>/delete/",
        views.ServerReservation6DeleteView.as_view(),
        name="server_reservation6_delete",
    ),
    path(
        "servers/<int:pk>/leases4/sync/",
        views.ServerLease4SyncView.as_view(),
        name="server_lease4_sync",
    ),
    path(
        "servers/<int:pk>/leases6/sync/",
        views.ServerLease6SyncView.as_view(),
        name="server_lease6_sync",
    ),
    path(
        "servers/<int:pk>/reservations4/sync/",
        views.ServerReservation4SyncView.as_view(),
        name="server_reservation4_sync",
    ),
    path(
        "servers/<int:pk>/reservations6/sync/",
        views.ServerReservation6SyncView.as_view(),
        name="server_reservation6_sync",
    ),
    path(
        "servers/<int:pk>/reservations4/bulk-sync/",
        views.ServerReservation4BulkSyncView.as_view(),
        name="server_reservation4_bulk_sync",
    ),
    path(
        "servers/<int:pk>/reservations6/bulk-sync/",
        views.ServerReservation6BulkSyncView.as_view(),
        name="server_reservation6_bulk_sync",
    ),
    path(
        "servers/<int:pk>/reservations4/import/",
        views.ServerReservation4BulkImportView.as_view(),
        name="server_reservation4_bulk_import",
    ),
    path(
        "servers/<int:pk>/reservations6/import/",
        views.ServerReservation6BulkImportView.as_view(),
        name="server_reservation6_bulk_import",
    ),
    path(
        "servers/<int:pk>/leases4/import/",
        views.ServerLease4BulkImportView.as_view(),
        name="server_lease4_bulk_import",
    ),
    path(
        "servers/<int:pk>/leases6/import/",
        views.ServerLease6BulkImportView.as_view(),
        name="server_lease6_bulk_import",
    ),
    path(
        "servers/<int:pk>/subnets4/<int:subnet_id>/pools/add/",
        views.ServerSubnet4PoolAddView.as_view(),
        name="server_subnet4_pool_add",
    ),
    path(
        "servers/<int:pk>/subnets4/<int:subnet_id>/pools/<path:pool>/delete/",
        views.ServerSubnet4PoolDeleteView.as_view(),
        name="server_subnet4_pool_delete",
    ),
    path(
        "servers/<int:pk>/subnets6/<int:subnet_id>/pools/add/",
        views.ServerSubnet6PoolAddView.as_view(),
        name="server_subnet6_pool_add",
    ),
    path(
        "servers/<int:pk>/subnets6/<int:subnet_id>/pools/<path:pool>/delete/",
        views.ServerSubnet6PoolDeleteView.as_view(),
        name="server_subnet6_pool_delete",
    ),
    path(
        "servers/<int:pk>/subnets4/add/",
        views.ServerSubnet4AddView.as_view(),
        name="server_subnet4_add",
    ),
    path(
        "servers/<int:pk>/subnets4/<int:subnet_id>/edit/",
        views.ServerSubnet4EditView.as_view(),
        name="server_subnet4_edit",
    ),
    path(
        "servers/<int:pk>/subnets4/<int:subnet_id>/delete/",
        views.ServerSubnet4DeleteView.as_view(),
        name="server_subnet4_delete",
    ),
    path(
        "servers/<int:pk>/subnets4/<int:subnet_id>/wipe/",
        views.ServerSubnet4WipeView.as_view(),
        name="server_subnet4_wipe_leases",
    ),
    path(
        "servers/<int:pk>/subnets6/add/",
        views.ServerSubnet6AddView.as_view(),
        name="server_subnet6_add",
    ),
    path(
        "servers/<int:pk>/subnets6/<int:subnet_id>/edit/",
        views.ServerSubnet6EditView.as_view(),
        name="server_subnet6_edit",
    ),
    path(
        "servers/<int:pk>/subnets6/<int:subnet_id>/delete/",
        views.ServerSubnet6DeleteView.as_view(),
        name="server_subnet6_delete",
    ),
    path(
        "servers/<int:pk>/subnets6/<int:subnet_id>/wipe/",
        views.ServerSubnet6WipeView.as_view(),
        name="server_subnet6_wipe_leases",
    ),
    path(
        "servers/<int:pk>/subnets4/<int:subnet_id>/options/",
        views.ServerSubnet4OptionsEditView.as_view(),
        name="server_subnet4_options_edit",
    ),
    path(
        "servers/<int:pk>/subnets6/<int:subnet_id>/options/",
        views.ServerSubnet6OptionsEditView.as_view(),
        name="server_subnet6_options_edit",
    ),
    path(
        "servers/<int:pk>/dhcp4/enable/",
        views.ServerDHCP4EnableView.as_view(),
        name="server_dhcp4_enable",
    ),
    path(
        "servers/<int:pk>/dhcp4/disable/",
        views.ServerDHCP4DisableView.as_view(),
        name="server_dhcp4_disable",
    ),
    path(
        "servers/<int:pk>/dhcp6/enable/",
        views.ServerDHCP6EnableView.as_view(),
        name="server_dhcp6_enable",
    ),
    path(
        "servers/<int:pk>/dhcp6/disable/",
        views.ServerDHCP6DisableView.as_view(),
        name="server_dhcp6_disable",
    ),
    path(
        "servers/<int:pk>/dhcp4/options/",
        views.ServerDHCP4OptionsEditView.as_view(),
        name="server_dhcp4_options_edit",
    ),
    path(
        "servers/<int:pk>/dhcp6/options/",
        views.ServerDHCP6OptionsEditView.as_view(),
        name="server_dhcp6_options_edit",
    ),
    path(
        "servers/<int:pk>/shared-networks4/add/",
        views.ServerSharedNetwork4AddView.as_view(),
        name="server_shared_network4_add",
    ),
    path(
        "servers/<int:pk>/shared-networks6/add/",
        views.ServerSharedNetwork6AddView.as_view(),
        name="server_shared_network6_add",
    ),
    path(
        "servers/<int:pk>/shared-networks4/<str:network_name>/delete/",
        views.ServerSharedNetwork4DeleteView.as_view(),
        name="server_shared_network4_delete",
    ),
    path(
        "servers/<int:pk>/shared-networks6/<str:network_name>/delete/",
        views.ServerSharedNetwork6DeleteView.as_view(),
        name="server_shared_network6_delete",
    ),
    path(
        "servers/<int:pk>/shared-networks4/<str:network_name>/edit/",
        views.ServerSharedNetwork4EditView.as_view(),
        name="server_shared_network4_edit",
    ),
    path(
        "servers/<int:pk>/shared-networks6/<str:network_name>/edit/",
        views.ServerSharedNetwork6EditView.as_view(),
        name="server_shared_network6_edit",
    ),
    path(
        "servers/<int:pk>/dhcp4/option-def/",
        views.ServerOptionDef4View.as_view(),
        name="server_option_def4",
    ),
    path(
        "servers/<int:pk>/dhcp6/option-def/",
        views.ServerOptionDef6View.as_view(),
        name="server_option_def6",
    ),
    path(
        "servers/<int:pk>/dhcp4/option-def/add/",
        views.ServerOptionDef4AddView.as_view(),
        name="server_option_def4_add",
    ),
    path(
        "servers/<int:pk>/dhcp6/option-def/add/",
        views.ServerOptionDef6AddView.as_view(),
        name="server_option_def6_add",
    ),
    path(
        "servers/<int:pk>/dhcp4/option-def/<int:code>/<str:space>/delete/",
        views.ServerOptionDef4DeleteView.as_view(),
        name="server_option_def4_delete",
    ),
    path(
        "servers/<int:pk>/dhcp6/option-def/<int:code>/<str:space>/delete/",
        views.ServerOptionDef6DeleteView.as_view(),
        name="server_option_def6_delete",
    ),
    path("servers/<int:pk>/", include(get_model_urls("netbox_kea", "server"))),
    path(
        "ip-addresses/<int:pk>/kea-reservations/",
        views.IPAddressKeaReservationsView.as_view(),
        name="ipaddress_kea_reservations",
    ),
)
