# SPDX-FileCopyrightText: 2023 Devon Mar <devon-mar@users.noreply.github.com>
# SPDX-FileCopyrightText: 2026 Marcin Zieba <marcinpsk@gmail.com>
# SPDX-License-Identifier: Apache-2.0
# Generated by Django 4.1.8 on 2023-05-15 04:00

from django.db import migrations, models


# netbox_kea tables stay in main, so branch migrate fakes this migration (ADR 0007).
fake_on_branch = True


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_kea', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='server',
            name='dhcp4',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='dhcp6',
            field=models.BooleanField(default=True),
        ),
    ]
