# Generated by Django 5.2.10 on 2026-03-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_kea', '0003_server_dual_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ('name',), 'permissions': [('bulk_delete_lease_from_server', 'Can bulk delete DHCP leases from server')]},
        ),
    ]
