# Generated by Django 5.2.13 on 2026-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_kea', '0010_sync_prefix_range_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='persist_config',
            field=models.BooleanField(
                default=True,
                help_text=(
                    "When enabled, Kea's configuration file is automatically saved "
                    "(<code>config-write</code>) after each change so modifications survive a "
                    "Kea daemon restart. Disable if Kea configuration is managed externally "
                    "(e.g. Ansible, Puppet) or if you manage persistence manually."
                ),
                verbose_name='Persist configuration',
            ),
        ),
    ]
