# Generated by Django 5.2.13 on 2026-04-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0086_gfk_indexes'),
        ('netbox_kea', '0010_syncconfig_sync_type_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='sync_vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipam.vrf'),
        ),
    ]
