# Generated by Django 5.2.13 on 2026-04-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_kea', '0011_server_sync_vrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='sync_ip_ranges_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='sync_leases_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='sync_prefixes_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='sync_reservations_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
