# Generated by Django 6.0.8 on 2026-08-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_kea', '0013_server_sync_dhcp_plugin_enabled_keadhcplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='keadhcplink',
            name='kea_identity',
            field=models.CharField(blank=True, max_length=393, null=True),
        ),
        migrations.AddConstraint(
            model_name='keadhcplink',
            constraint=models.UniqueConstraint(condition=models.Q(('kea_identity__isnull', False)), fields=('server', 'family', 'kea_identity'), name='keadhcplink_unique_reservation_identity'),
        ),
    ]
