# Generated by Django 6.0.8 on 2026-08-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_kea', '0014_keadhcplink_kea_identity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='keadhcplink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kea_identity__isnull', True), ('kea_subnet_id__isnull', False)), models.Q(('kea_identity__isnull', False), ('kea_subnet_id__isnull', True)), _connector='OR'), name='keadhcplink_one_identity_kind'),
        ),
    ]
