# Generated by Django 6.0.8 on 2026-08-18 10:15

from django.db import migrations, models


def remove_invalid_identity_links(apps, schema_editor):
    """Remove links whose Kea target cannot be identified unambiguously."""
    KeaDhcpLink = apps.get_model("netbox_kea", "KeaDhcpLink")
    invalid_identity = (
        models.Q(kea_subnet_id__isnull=True, kea_identity__isnull=True)
        | models.Q(kea_subnet_id__isnull=False, kea_identity__isnull=False)
        | models.Q(kea_subnet_id__isnull=True, kea_identity="")
    )
    KeaDhcpLink.objects.using(schema_editor.connection.alias).filter(invalid_identity).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_kea', '0014_keadhcplink_kea_identity'),
    ]

    operations = [
        migrations.RunPython(remove_invalid_identity_links, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='keadhcplink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kea_identity__isnull', True), ('kea_subnet_id__isnull', False)), models.Q(('kea_identity__gt', ''), ('kea_subnet_id__isnull', True)), _connector='OR'), name='keadhcplink_one_identity_kind'),
        ),
    ]
