# SPDX-FileCopyrightText: 2026 Marcin Zieba <marcinpsk@gmail.com>
# SPDX-License-Identifier: Apache-2.0
# Generated by Django 6.1 on 2026-10-01 18:31

from django.db import migrations, models


# The plugin tables remain in main (ADR 0007).
fake_on_branch = True


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_kea', '0019_ipamownershiplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='sync_deprecate_prefixes_and_ranges',
            field=models.BooleanField(default=False),
        ),
    ]
