# SPDX-FileCopyrightText: 2026 Marcin Zieba <marcinpsk@gmail.com>
# SPDX-License-Identifier: Apache-2.0
# Generated by Django 6.1 on 2026-10-02 08:21

from django.db import migrations, models


fake_on_branch = True


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_kea', '0020_server_deprecate_prefixes_and_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipamownershiplink',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='ipam_first_complete_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ipam_initial_observations',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
