# SPDX-FileCopyrightText: 2026 Marcin Zieba <marcinpsk@gmail.com>
# SPDX-License-Identifier: Apache-2.0
# Generated by Django 6.1 on 2026-10-04 05:49

from django.db import migrations, models


fake_on_branch = True


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_kea', '0021_ipamownershiplink_adopted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keadhcplink',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
