# SPDX-FileCopyrightText: 2026 Marcin Zieba <marcinpsk@gmail.com>
# SPDX-License-Identifier: Apache-2.0
# Generated by Django 6.1.1 on 2026-10-08 14:00

from django.db import migrations, models


fake_on_branch = True


def classify_dhcpv4_lease_links(apps, schema_editor):
    """DHCPv4 has only address leases; a DHCPv6 lease link stays unclassified until fresh evidence classifies it."""
    link_model = apps.get_model("netbox_kea", "IPAMOwnershipLink")
    links = link_model.objects.using(schema_editor.connection.alias)
    links.filter(source="lease", family=4).update(allocation_kind="address")


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_kea', '0022_dhcp_import_mapping_history'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ipamownershiplink',
            name='ipamownershiplink_source',
        ),
        migrations.AddField(
            model_name='ipamownershiplink',
            name='allocation_kind',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='ipamownershiplink',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['lease', 'reservation', 'subnet', 'pool', 'delegated-prefix', 'lease-prefix'])), name='ipamownershiplink_source'),
        ),
        migrations.AddConstraint(
            model_name='ipamownershiplink',
            constraint=models.CheckConstraint(condition=models.Q(('allocation_kind', ''), ('source', 'lease'), _connector='OR'), name='ipamownershiplink_allocation_kind'),
        ),
        migrations.RunPython(classify_dhcpv4_lease_links, migrations.RunPython.noop),
    ]
